apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: im
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - args:
          - /usr/local/bin/etcd
          - --name
          - etcd0
          - --data-dir
          - /etcd-data
          - --listen-client-urls
          - http://0.0.0.0:2379
          - --advertise-client-urls
          - http://0.0.0.0:2379
          - --listen-peer-urls
          - http://0.0.0.0:2380
          - --initial-advertise-peer-urls
          - http://0.0.0.0:2380
          - --initial-cluster
          - etcd0=http://0.0.0.0:2380
          - --initial-cluster-token
          - tkn
          - --initial-cluster-state
          - new
          env:
            - name: ETCDCTL_API
              value: "3"
          image: swr.cn-north-4.myhuaweicloud.com/wcmdh/etcd:latest
          name: etcd
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - mountPath: /etc/timezone
              name: etcd-claim0
            - mountPath: /etc/localtime
              name: etcd-claim1
          resources:
            limits:
              cpu: '200m'
              memory: '128Mi'
            requests:
              cpu: '10m'
              memory: '1Mi'
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      volumes:
        - name: etcd-claim0
          hostPath: 
            path: /etc/timezone
        - name: etcd-claim1
          hostPath: 
            path: /etc/localtime
