apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: im
spec:
  ports:
    - name: "9898"
      port: 9898
      targetPort: 2379
    - name: "9899"
      port: 9899
      targetPort: 2380
  selector:
    app: etcd
  type: ClusterIP
