apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: im
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - env:
          - name: TZ
            value: Asia/Shanghai
          image: swr.cn-north-4.myhuaweicloud.com/wcmdh/zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /etc/localtime
              name: zookeeper-claim0
          resources:
            limits:
              cpu: '200m'
              memory: '256Mi'
            requests:
              cpu: '10m'
              memory: '1Mi'
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      volumes:
        - name: zookeeper-claim0
          hostPath: 
            path: /etc/localtime
