apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: im
spec:
  ports:
    - name: "9902"
      port: 9902
      targetPort: 9092
    - name: "9903"
      port: 9903
      targetPort: 9093
  selector:
    app: kafka
  type: ClusterIP
