apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  ports:
    - name: "12379"
      port: 12379
      targetPort: 2379
    - name: "12380"
      port: 12380
      targetPort: 2380
  selector:
    app: etcd
  type: ClusterIP
