apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: openIM
          image: swr.cn-east-3.myhuaweicloud.com/fusionhealth/mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
            - containerPort: 33060
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
            - mountPath: /etc/localtime
              name: mysql-claim1
          resources:
            requests:
              cpu: 30m
              memory: 1Mi
            limits:
              cpu: 120m
              memory: 576Mi
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          hostPath: 
            path: /data/mysql
        - name: mysql-claim1
          hostPath: 
            path: /etc/localtime
