apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - args:
            - redis-server
            - --requirepass
            - openIM
            - --appendonly
            - "yes"
          env:
            - name: TZ
              value: Asia/Shanghai
          image: swr.cn-east-3.myhuaweicloud.com/fusionhealth/redis:latest
          name: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-claim0
          resources:
            requests:
              cpu: 60m
              memory: 1Mi
            limits:
              cpu: 180m
              memory: 96Mi
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      volumes:
        - name: redis-claim0
          hostPath: 
            path: /data/redis
