---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-transfer
  namespace: im
spec:
  selector:
    matchLabels:
      app: msg-transfer # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: msg-transfer # 标签
    spec:
      # hostAliases:
      # - ip: "116.63.8.212"
      #   hostnames:
      #   - "kafka-dev"
      containers:
      - name: msg-transfer
        image: swr.cn-north-4.myhuaweicloud.com/wcmdh/openim/msg_transfer:v2.3.0
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"   
        resources:
          requests: {}
          limits:
            cpu: 250m
            memory: 1024Mi    
      imagePullSecrets:
        - name: default-secret     
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
