---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend
  namespace: im
spec:
  selector:
    matchLabels:
      app: friend # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: friend # 标签
    spec:
      containers:
      - name: friend
        image: swr.cn-north-4.myhuaweicloud.com/wcmdh/openim/friend:v2.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 10120
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"   
      imagePullSecrets:
        - name: default-secret  
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新

