apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - env:
          - name: TZ
            value: Asia/Shanghai
          - name: wiredTigerCacheSizeGB
            value: "1"
          image: swr.cn-east-3.myhuaweicloud.com/fusionhealth/mongo:4.0
          name: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim0
            - mountPath: /data/logs
              name: mongodb-claim1
            - mountPath: /etc/mongo
              name: mongodb-claim2
          resources:
            requests:
              cpu: 110m
              memory: 1Mi
            limits:
              cpu: 330m
              memory: 512Mi
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      volumes:
        - name: mongodb-claim0
          hostPath: 
            path: /data/mongo/db
        - name: mongodb-claim1
          hostPath: 
            path: /data/mongo/logs
        - name: mongodb-claim2
          hostPath: 
            path: /data/mongo/conf
