apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
    - name: "37017"
      port: 37017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
