apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_CREATE_TOPICS
            value: ws2ms_chat:8:1,ms2ps_chat:8:1,msg_to_mongo:8:1
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: TZ
            value: Asia/Shanghai
          image: swr.cn-east-3.myhuaweicloud.com/fusionhealth/kafka
          name: kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources:
            requests:
              cpu: 220m
              memory: 1Mi
            limits:
              cpu: 1320m
              memory: 1536Mi
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
